/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 19-May-2018 22:39:16
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2018a/extern/include/tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
  8.524862569546e-05,0.0003409945027818,0.0005114917541727,0.0003409945027818,
  8.524862569546e-05
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.465327146521,    4.534318332006,   -2.652582989652,
     0.5849557821783
};
