/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 19-May-2018 18:07:00
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2018a/extern/include/tmwtypes.h 
 */
const int NL = 7;
const real64_T NUM[7] = {
  6.581228666848e-06,3.948737200109e-05,9.871843000272e-05, 0.000131624573337,
  9.871843000272e-05,3.948737200109e-05,6.581228666848e-06
};
const int DL = 7;
const real64_T DEN[7] = {
                   1,   -4.844130898248,    9.869891194687,   -10.81429684333,
      6.714475128551,   -2.238311133546,   0.3127937505226
};
